#!/usr/bin/env bash
# ALWAYS ON - rollback.sh: undo provision.sh stages, non-destructively.
#
#   ./scripts/provision/rollback.sh --list
#   ./scripts/provision/rollback.sh            # dry run: prints every action
#   ./scripts/provision/rollback.sh --yes      # apply
#
# DESIGN RULES (AGENTS.md, README 4.1):
#   * DRY RUN BY DEFAULT, mirroring provision.sh. Undo is as dangerous as the
#     action, so it must be deliberate.
#   * Never removes data/, secrets/, images, volumes or podman networks.
#     Removing a network would strand containers; removing a secret would make
#     services unstartable and cannot be undone. Those stages are REPORTED, not
#     undone - see the NEEDS OPERATOR lines below.
#   * Only removes what provision.sh itself installed, and only names a unit
#     when it can be attributed to a domain in quadlet/.
#   * Uninstalling a package is printed as a command, never run: shared
#     libraries have no safe dependency-respecting undo, and rule 3 forbids
#     deleting without approval.
set -uo pipefail

AO_ROOT="${AO_ROOT:-/ALWAYSON}"
LEDGER="$AO_ROOT/logs/operations/provision-ledger.jsonl"
ASSUME_YES=0
LIST_ONLY=0

for a in "$@"; do
  case "$a" in
    --yes)     ASSUME_YES=1 ;;
    --dry-run) ASSUME_YES=0 ;;
    --list)    LIST_ONLY=1 ;;
    -h|--help) sed -n '2,19p' "$0"; exit 0 ;;
    *) echo "unknown option: $a (try --help)" >&2; exit 2 ;;
  esac
done

say() { printf '%s\n' "$*"; }
exec_cmd() {
  # exec_cmd STAGE COMMAND... - the only path that actually mutates.
  if [ "$ASSUME_YES" -eq 1 ]; then
    printf '  [stage %s] $ %s\n' "$1" "${*:2}"
    "${@:2}"
    return $?
  fi
  # Dry run: print once, marked, with no second duplicate line.
  printf '  [stage %s] [dry-run] %s\n' "$1" "${*:2}"
  return 0
}
have() { command -v "$1" >/dev/null 2>&1; }

say "=== ALWAYS ON provisioner rollback ==="
say "mode : $([ "$ASSUME_YES" -eq 1 ] && echo APPLY || echo 'DRY-RUN (pass --yes to apply)')"
say "repo : $AO_ROOT"

if [ "$LIST_ONLY" -eq 1 ]; then
  cat <<'EOF'
stage  what it undoes                          needs operator?
  90   nothing (regenerated artefacts)         no  - informational only
  70   nothing - stage 70 never restores        no  - REPORT ONLY
  60   nothing - stage 60 only checks presence  no  - secrets never removed
  55   restic backup units installed from       no
       systemd/backup/ (stop, disable, remove
       the 6 unit files, daemon-reload)
  50   Quadlet unit files deployed flat, per   no  - per domain, and ONLY the
       domain, via deploy/rollback-domain.sh    unit files named in quadlet/
  40   vendor blobs - prints the manifest ids  YES - a drift/refused file or a
       for the operator to decide              fetched AppImage; deleting is
                                                rule 3
  30   snaps and the flatpak - PRINTS the       YES - rule 3, and a snap may be
       remove commands, does not run them       referenced by quadlet units
  20   apt repositories provisioned by stage    no  - removes the .list/.sources
       10 (repo files + keyrings)              and keyring provision.sh added
  10   nothing: stage 10 has no rollback of     no  - it only ADDS. Undo is
       its own                                   stage 20's repo removal.
EOF
  exit 0
fi
say ""
say "--- stage 90: verification artefacts (nothing to undo)"
say "  Regenerated by re-running provision.sh stage 90. No removal."
say ""

say "--- stage 70: persistent data (NEEDS OPERATOR - not undone)"
for d in ardupilot corda-install sim-fabrication sales mapping; do
  [ -d "$AO_ROOT/data/$d" ] && say "  PRESERVED: data/$d ($(du -sh "$AO_ROOT/data/$d" 2>/dev/null | cut -f1))"
done
say "  Stage 70 never restored anything, so there is nothing to undo. Data is"
say "  never removed by this script (AGENTS.md rule 2/3)."
say ""

say "--- stage 60: secrets (NEEDS OPERATOR - not undone)"
say "  Stage 60 only CHECKED presence. Secrets are never removed: the values"
say "  live in the wallet and in ~/.local/share/ao-secrets/ and are not"
say "  reproducible from this repository."
say ""

say "--- stage 55: restic backup units"
if [ -d "$AO_ROOT/systemd/backup" ]; then
  for f in "$AO_ROOT"/systemd/backup/*.service "$AO_ROOT"/systemd/backup/*.timer; do
    [ -f "$f" ] || continue
    b="$(basename "$f")"
    if systemctl list-unit-files "$b" 2>/dev/null | grep -q "$b"; then
      exec_cmd 55 systemctl disable --now "$b"
    fi
    if [ -f "/etc/systemd/system/$b" ]; then
      exec_cmd 55 sudo rm -f "/etc/systemd/system/$b"
    fi
  done
  exec_cmd 55 sudo systemctl daemon-reload
fi
say "  WARNING: removing the backup timer stops scheduled backups. Prefer"
say "--- stage 50: Quadlet unit files (per domain)"
if [ -d "$AO_ROOT/quadlet" ]; then
  for d in "$AO_ROOT"/quadlet/*/; do
    n="$(basename "$d")"
    # Deploy only considers a domain that actually holds quadlet source.
    compgen -G "$d*.network" >/dev/null || compgen -G "$d*.container" >/dev/null || continue
    if [ -x "$AO_ROOT/scripts/deploy/rollback-domain.sh" ]; then
      if [ "$ASSUME_YES" -eq 1 ]; then
        "$AO_ROOT/scripts/deploy/rollback-domain.sh" "$n" || say "  WARNING: rollback of domain $n did not complete"
      else
        say "  [stage 50] [dry-run] $AO_ROOT/scripts/deploy/rollback-domain.sh $n"
      fi
    fi
  done
fi
say "  rollback-domain.sh removes ONLY the unit files named in quadlet/<domain>/"
say "  from ~/.config/containers/systemd/. It never rm -r's that directory,"
say "  which holds every other domain."
say ""

say "--- stage 40: vendor blobs (NEEDS OPERATOR - not undone)"
if [ -f "$AO_ROOT/config/build-update/vendor-binaries.yaml" ]; then
  say "  Manifest: config/build-update/vendor-binaries.yaml"
  say "  Entries this script will NOT remove without an explicit operator"
  say "  decision (rule 3 - each is a downloaded artefact outside git):"
  python3 - "$AO_ROOT/config/build-update/vendor-binaries.yaml" <<'PY'
import sys, yaml
reg = yaml.safe_load(open(sys.argv[1])) or {}
# The measured top-level keys of this manifest are exactly:
# schema_version, measured_utc, measured_on, vendor_binaries.
# Guessing 'binaries'/'appimages' here printed an empty list and looked like a
# clean "nothing to remove" - a zero from a parser, not a measurement.
if not isinstance(reg, dict) or "vendor_binaries" not in reg:
    print(f"  MANIFEST SHAPE CHANGED, keys={sorted(reg) if isinstance(reg, dict) else type(reg)}")
    raise SystemExit(1)
for e in reg["vendor_binaries"] or []:
    if isinstance(e, dict):
        print(f"    - {e.get('id','?')}  target={e.get('path','?')}")
PY
else
  # Do NOT fall through silently. An absent manifest must say so, otherwise
  # this stage prints nothing and reads as "no vendor blobs to remove".
  say "  NO MANIFEST at $AO_ROOT/config/build-update/vendor-binaries.yaml."
  say "  This is NOT 'nothing to remove'. On a fresh clone it means stage 40's"
  say "  inventory has no source of truth here; install the repo at \$AO_ROOT."
fi
say ""

say "--- stage 30: snaps and flatpak (NEEDS OPERATOR - commands printed only)"
if have snap; then
  say "  To remove, the operator runs (NOT executed here):"
  for s in brave firefox cups orcaslicer mesa-2404; do
    snap list 2>/dev/null | awk '{print $1}' | grep -qx "$s" && say "    sudo snap remove $s"
  done
fi
if have flatpak; then
  flatpak list --app --columns=application 2>/dev/null | grep -qx com.usebottles.bottles \
    && say "    flatpak uninstall com.usebottles.bottles"
fi
say "  Not run automatically: a snap removal is a delete (rule 3), and the"
say "  coreNN / theme snaps are shared with the desktop session."
say ""
say "--- stage 20: apt repositories added by stage 10"
for k in vscodium-archive-keyring steam google-chrome microsoft-edge \
         nvidia-container-toolkit-keyring; do
  [ -f "/etc/apt/keyrings/$k.gpg" ] && say "  would remove: /etc/apt/keyrings/$k.gpg"
done
for l in vscodium.list steam-stable.list steam-beta.list github-cli.list \
         nvidia-container-toolkit.list ros2.list gazebo-stable.list \
         nodesource.sources google-chrome.sources microsoft-edge.sources; do
  [ -f "/etc/apt/sources.list.d/$l" ] && say "  would remove: /etc/apt/sources.list.d/$l"
done
say "  Printed, not executed: removing a repository can strand every package"
say "  installed from it, and that cannot be undone by any script here."
say ""

say "--- stage 10: nothing to undo"
say "  Stage 10 only ADDS repositories. Its undo is stage 20's removal list."
say ""

if [ -f "$LEDGER" ]; then
  say "provision ledger: $LEDGER"
  say "Stages that actually ran, from that ledger:"
  python3 - "$LEDGER" <<'PY'
import json, sys, collections
seen = collections.Counter()
for line in open(sys.argv[1]):
    line = line.strip()
    if not line:
        continue
    try:
        seen[json.loads(line)["stage"]] += 1
    except (ValueError, KeyError):
        continue
for k in sorted(seen):
    print(f"  stage {k}: {seen[k]} step(s) recorded")
PY
fi
say ""
if [ "$ASSUME_YES" -eq 1 ]; then
  say "rollback complete. Re-read the warnings: the NEEDS OPERATOR stages were NOT undone."
else
  say "dry run only. Nothing was changed. Re-run with --yes to apply."
fi