#!/usr/bin/env python3
"""
ALWAYS ON - turn an intake KIT REQUEST into an autofill record.

Reads the text extracted by intake-kit-request-pdf.sh (or a pasted/forwarded
email body) and produces the JSON record that autofill-handoff-form.py
consumes. Pure standard library.

    intake-request-record.py <extracted.txt> <out.json> [--items items.csv]

The website composes a request in a fixed shape (README 15.1.2):

    SUBJECT: 300X3-WEBREQUEST-
    NAME: <name>
    EMAIL: <email>
    KIT REQUESTED: <selected kits>
    COMMENTS: <comments>
    THIS IS A REQUEST FOR INFORMATION, NOT A CONTRACT

A missing NAME or EMAIL is reported as incomplete rather than guessed: the
README sends an incomplete request back by email asking for the rest. This
script never invents a field it did not read.

Free-text kit labels are resolved against an optional CSV of
sku,category,name so the PDF prints a real SKU. An unresolved label is kept
verbatim in item_name and flagged, never silently dropped.

No payment data is read, stored or emitted (Section 4.1 rule 7).
"""
import argparse
import csv
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REQUIRED = ("name", "email")


def parse(text: str) -> dict:
    """Pull the labelled fields out of a request body."""
    found, comments, in_comments = {}, [], False

    for raw in text.splitlines():
        line = raw.rstrip()
        if in_comments:
            if re.match(r"^\s*THIS IS A REQUEST FOR INFORMATION", line, re.I):
                in_comments = False
                continue
            comments.append(line)
            continue

        match = re.match(r"^\s*([A-Z ]+)\s*:\s*(.*)$", line)
        if not match:
            continue
        label, value = match.group(1).strip().upper(), match.group(2).strip()

        if label == "COMMENTS":
            in_comments = True
            if value:
                comments.append(value)
            continue
        if label == "SUBJECT":
            found["subject"] = value
        elif label in ("NAME", "EMAIL"):
            found[label.lower()] = value
        elif label == "KIT REQUESTED":
            found["kits"] = value

    if comments:
        found["comments"] = "\n".join(comments).strip()
    return found


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("source", help="extracted request text")
    ap.add_argument("out")
    ap.add_argument("--items", help="catalogue CSV: sku,category,name")
    ap.add_argument("--request-number")
    ap.add_argument("--intake-number")
    ap.add_argument("--sha256")
    args = ap.parse_args()

    source = Path(args.source)
    if not source.is_file():
        print(f"ERROR: not found: {source}", file=sys.stderr)
        return 2

    text = source.read_text(encoding="utf-8", errors="replace")
    found = parse(text)
    catalogue = load_catalogue(args.items)

    items, unresolved = [], []
    for label in split_items(found.get("kits", "")):
        row = catalogue.get(label.lower())
        if row:
            items.append({
                "item_category": row.get("category", ""),
                "item_name": row.get("name", label),
                "item_sku": row.get("sku", ""),
                "item_quantity": "1",
                "item_options": "",
                "item_notes": "",
            })
        else:
            unresolved.append(label)
            items.append({
                "item_category": "Unresolved",
                "item_name": label,
                "item_sku": "",
                "item_quantity": "1",
                "item_options": "",
                "item_notes": "Not in catalogue - operator review required",
            })

    missing = [f for f in REQUIRED if not found.get(f)]
    now = datetime.now(timezone.utc)
    request_number = args.request_number or (
        "REQ-" + now.strftime("%Y-%m-%d%H%M%S")
    )
    intake_number = args.intake_number or (
        "INT-" + now.strftime("%Y%m%dT%H%M%SZ")
    )

    if missing:
        read_result = (
            "INCOMPLETE - missing " + ", ".join(missing)
            + ". Request the remainder by email before this becomes a work order."
        )
    elif unresolved:
        read_result = (
            "Read complete, but " + str(len(unresolved)) + " item(s) are not in the "
            "catalogue: " + ", ".join(unresolved)
            + ". Resolve the SKU before quoting."
        )
    else:
        read_result = (
            "Read complete. All items resolved to a catalogue SKU. This is an "
            "inquiry; it becomes a work order only after operator review."
        )

    record = {
        "_comment": "Generated by intake-request-record.py. Review before use.",
        "intake_number": intake_number,
        "request_number": request_number,
        "subject": found.get("subject", ""),
        "source_file": source.name,
        "source_sha256": args.sha256 or "",
        "received_at": now.strftime("%Y-%m-%d %H:%M UTC"),
        "requester_name": found.get("name", ""),
        "requester_email": found.get("email", ""),
        "requester_phone": "",
        "delivery_address": "",
        "comments": found.get("comments", ""),
        "read_result": read_result,
        "flag_complete": not missing and not unresolved,
        "flag_incomplete": bool(missing),
        "flag_unresolved": bool(unresolved),
        "flag_duplicate": False,
        "sale_logged": "false",
        "corda_state": "NOT_SUBMITTED",
        "classification": "Inquiry",
        "review_legible": False,
        "review_identity": False,
        "review_not_duplicate": False,
        "review_options_reviewed": False,
        "tables": {"items": items},
        "schema_version": "1.0",
    }

    out = Path(args.out)
    out.write_text(
        json.dumps(record, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"OK: {out}")
    print(f"request_number={request_number}")
    print(f"items={len(items)} unresolved={len(unresolved)}")
    for label in unresolved:
        print(f"UNRESOLVED (not in catalogue): {label}")
    if missing:
        print(
            "INCOMPLETE - missing " + ", ".join(missing)
            + "; request the remainder by email per README 7.1.1"
        )
        return 4
    print("READY: complete request, awaiting operator review")
    return 0


def load_catalogue(path) -> dict:
    """sku,category,name -> row, keyed by lowercase name for matching."""
    if not path:
        return {}
    rows = {}
    with Path(path).open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            key = (row.get("name") or "").strip().lower()
            if key:
                rows[key] = row
    return rows


def split_items(value: str) -> list:
    """Split a kits field on commas/semicolons, or newlines."""
    if not value:
        return []
    return [p.strip() for p in re.split(r"[,;\n]+", value) if p.strip()]


if __name__ == "__main__":
    sys.exit(main())