#!/usr/bin/env bash
# ALWAYS ON - check-deployment-conformance.sh
#
# Verifies that the deployed systemd/Quadlet state matches the repository and
# the README. Written 2026-10-01 after an audit found that ao-grafana and
# ao-metabase were still reading EnvironmentFile from a secrets directory that
# had been renamed days earlier: both were healthy only because a stale copy of
# the directory happened to remain on disk. Nothing in the repository caught
# that, and check-secrets-exposure.sh cannot, because it only inspects tracked
# content rather than what is actually deployed.
#
# Checks:
#   1. every deployed ao-* unit has a source file in quadlet/
#   2. every deployed unit is byte-identical to its repository source
#   3. no deployed unit references a retired 300x3-/alwayson- path
#   4. every unit named in the README as active is active
#   5. every ao-* network in the registry exists
#   6. every container is owned by an ao-* unit (ownership, not name)
#
# Exit 42 on any failure, matching check-network-isolation.sh.
set -Eeuo pipefail
IFS=$'\n\t'
. /ALWAYSON/scripts/lib/common.sh

quadlet=/ALWAYSON/quadlet
unit_dirs=("$HOME/.config/containers/systemd" "$HOME/.config/systemd/user")
fails=0
note() { printf '  %s\n' "$*" >&2; }

# Units deliberately not tracked: incident diagnostics from 2026-09-30, not
# ALWAYS ON infrastructure. They write to ~/Desktop/SYSTEM LOCKOUT/.
# No units are exempt. The ao-font-* incident-diagnostic units are tracked in
# the repository too: the fontconfig cache corruption they guard against was
# repaired, but the related Plasma lockout-after-suspend problem is recorded
# as UNRESOLVED, so the units are live mitigation rather than history.

# --- 1 and 2: deployed units must exist in the repo and match --------------
# Generated units (podman-user-generator output) are excluded: they carry a
# banner line naming the generator, and the generator is what produces them
# from the .container files checked here. Comparing them to a repo source
# would be comparing generated output against generated output.
deployed=()
for d in "${unit_dirs[@]}"; do
  [ -d "$d" ] || continue
  while IFS= read -r f; do
    head -1 "$f" | grep -q 'Automatically generated by' && continue
    deployed+=("$f")
  done < <(find "$d" -maxdepth 1 -name 'ao-*' \( -name '*.container' -o -name '*.network' \
        -o -name '*.volume' -o -name '*.service' -o -name '*.path' -o -name '*.timer' \) 2>/dev/null)
done

for f in "${deployed[@]}"; do
  b=$(basename "$f")
  skip=0
  for u in "${untracked_ok[@]}"; do [ "$b" = "$u" ] && skip=1; done
  (( skip )) && continue
  src=$(find "$quadlet" -name "$b" -print -quit 2>/dev/null || true)
  if [[ -z "$src" ]]; then
    note "ERROR: deployed unit has no source in $quadlet: $b"
    fails=$((fails + 1))
    continue
  fi
  if ! diff -q "$src" "$f" >/dev/null 2>&1; then
    note "ERROR: deployed unit differs from repo source: $b"
    diff -u "$src" "$f" 2>&1 | head -8 | sed 's/^/      /' >&2
    fails=$((fails + 1))
  fi
done

# --- 3: no retired naming in anything deployed -----------------------------
for f in "${deployed[@]}"; do
  if grep -lE 'alwayson-|300x3-' "$f" >/dev/null 2>&1; then
    note "ERROR: retired naming in deployed unit: $(basename "$f")"
    grep -nE 'alwayson-|300x3-' "$f" | head -3 | sed 's/^/      /' >&2
    fails=$((fails + 1))
  fi
done

# --- 4: every enabled ao-* unit is active ----------------------------------
while IFS= read -r u; do
  [[ -z "$u" ]] && continue
  case "$u" in
    ao-ardupilot-sitl|ao-sim-fabrication) continue ;;  # on-demand by design
  esac
  # A oneshot unit is idle (inactive/dead) between runs by design, so
  # is-active is the wrong test for it. Such a unit is judged by whether it
  # last succeeded, and it must be reachable from a timer or path unit.
  utype=$(systemctl --user show "$u" -p Type --value 2>/dev/null || echo simple)
  if [[ "$utype" == "oneshot" ]]; then
    res=$(systemctl --user show "$u" -p Result --value 2>/dev/null || echo unknown)
    trig=$(systemctl --user show "$u" -p TriggeredBy --value 2>/dev/null || echo "")
    if [[ "$res" != "success" && "$res" != "done" ]]; then
      note "ERROR: oneshot last run did not succeed: $u (Result=$res)"
      fails=$((fails + 1))
    elif [[ -z "$trig" && "$res" != "success" ]]; then
      note "ERROR: oneshot has no timer/path and did not succeed: $u"
      fails=$((fails + 1))
    fi
    continue
  fi
  state=$(systemctl --user is-active "$u" 2>/dev/null || echo unknown)
  if [[ "$state" != "active" ]]; then
    note "ERROR: enabled but not active: $u ($state)"
    fails=$((fails + 1))
  fi
done < <(systemctl --user list-units --all --no-legend --plain 2>/dev/null \
           | awk '{print $1}' | grep -E '^ao-.*\.(service|timer|path)$' | sort -u)

# --- 5: registry networks all exist ----------------------------------------
while IFS= read -r net; do
  [[ -z "$net" ]] && continue
  podman network exists "$net" 2>/dev/null || {
    note "ERROR: registry network missing from podman: $net"
    fails=$((fails + 1)); }
done < <(awk '/internal=/{print $1}' /ALWAYSON/config/platform/network-cidrs.yaml 2>/dev/null | sort -u)

# --- 6: every container is owned by an ao-* unit ---------------------------
# Ownership, not the container's own name, is the test. The five Mastodon
# containers are named mastodon-* but are created and supervised by the
# ao-mastodon-* Quadlet units, so they are already subordinated to ao-* and
# need no recorded exception. A container with no owning unit at all is the
# real defect: nothing restarts it and it does not survive a reboot.
while IFS= read -r c; do
  [[ -z "$c" ]] && continue
  owner=$(podman inspect "$c" --format '{{index .Config.Labels "PODMAN_SYSTEMD_UNIT"}}' 2>/dev/null || echo "")
  if [[ -z "$owner" ]]; then
    note "ERROR: container has no owning systemd unit (will not restart or survive reboot): $c"
    fails=$((fails + 1))
  elif [[ "$owner" != ao-* ]]; then
    note "ERROR: container $c is owned by a non-ao unit: $owner"
    fails=$((fails + 1))
  fi
done < <(podman ps -a --format '{{.Names}}' 2>/dev/null)

if (( fails == 0 )); then
  echo "OK: deployed units match the repository; no retired naming; enabled units active; networks present; containers prefixed"
else
  echo "FAIL: $fails deployment conformance problem(s)" >&2
  exit 42
fi
